M48
; DRILL file {KiCad (6.0.7)} date Sun Oct  2 22:03:57 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-02T22:03:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.258Y-2.8895
X4.4855Y-2.8895
T2
X4.2851Y-5.2271
X4.4584Y-5.2271
T0
M30
